PRODUCT_TEMPLATE_ID = "d-3fc1696efc9545f9a9386b0a0375d9e3"
EMAIL_DATA_FILE = "email_data.json"
STYLE_FILE = "style.json"
FILES_PREFIX = "files/"

EMPLOYEE_NAME = "employee_name"
FROM_EMAIL = "from_email"
CUSTOMER_LIST = "customer_list"
PRODUCT_LIST = "product_list"
NAME = "name"
EMAIL = "email"
SUBJECT = "subject"

TODAY = "today"
CUSTOMER_NAME = "customer_name"
CUSTOMER_EMAIL = "customer_email"
TABLE_DATA = "table_data"

SENDER_NAME = "Sender_Name"
SENDER_ADDRESS = "Sender_Address"
SENDER_CITY = "Sender_City"
SENDER_STATE = "Sender_State"
NHST ="NHST"
OSLO = "Oslo"
NORWAY = "Norway"

